---
title: "BluePrint experiments meta analysis Notebook"
output: html_notebook
---



```{r fig1, fig.height = 3, fig.width = 3, fig.align = "center"}
library( ExpressionAtlas)

## loading generic functions 
source("/Users/suhaib/BaselineMetaAnalysis/OpenTargets/generic_functions.R")
## get blueprints expriments from exression atlas
atlasData <- getAtlasData(c("E-MTAB-3819", "E-MTAB-3827", "E-MTAB-4754"))

t<-atlasData
all <- vector()

for (i in names(t)) {
  expAcc <- i
  k <- t[[i]]
  exp <- k$rnaseq
  eCounts <- assays(exp)$counts
  samples<-colnames(eCounts)
  average.counts<-technical_replicate_average_bp(exp,expAcc,eCounts)
  all <- cbind(all,average.counts)
}

## sanity check 
head(all)
dim(all)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

```{r}
## filtering lower signals
filter <- rowSums(all>10)>=5
filtered <- all[filter,]
dim(filtered)
filterCols <- colSums(filtered == 0) / nrow(filtered) < 0.90
x <- x[filterCols]
filtered <- filtered[,filterCols]
filtered<-na.exclude(filtered)

filtered.genes<-setdiff(rownames(all),rownames(filtered))
write.table(filtered.genes,file="filtered_genes_blueprint.txt",sep="\t",col.names='NA')
```

```{r fig3, fig.height = 5, fig.width = 5, fig.align = "center"}
## tissue names
x<-as.factor(sapply(strsplit(colnames(filtered),split="_"),"[",3))

## coefficient of Variation
co.var <- function(x) ( 100*apply(x,1,sd)/rowMeans(x) ) 

## coefficient of variation across all the sammples
cov.allGenes<-na.omit(co.var(as.matrix(filtered)))

# Using threshold (1% qauntile) for identification of non vriable genes that has least cov.
cov.range<-seq(range(cov.allGenes)[1], range(cov.allGenes)[2], by = 10)

## identyfing number of genes changed acros several cov thresholds range
ngenes<-matrix()
for (i in seq_along(cov.range)){
  ngenes[i]<- sum((cov.allGenes<=cov.range[i])*1)
}

plot(cov.range,ngenes, xlab="Coefficient of Variation",type="b", ylab="Number of genes",pch=16,col="blue",main="")
#abline(v=summary(cov.range)[[2]],lwd=1,col="red")
abline(v=quantile(cov.range, c(.01))[[1]], lwd=1, col="red")
legend("bottomright",c("1% quantile"),lty=1, lwd=1, col="red")

# Using threshold (1% qauntile) for identification of non vriable genes that has least cov.
leastVar.genes<-rownames(as.matrix(sort(cov.allGenes[cov.allGenes < quantile(cov.range, c(.1))[[1]]])))

```

```{r fig5, fig.height = 8, fig.width = 8, fig.align = "center"}

library(EDASeq)
library(EDASeq)
library(ggplot2)
library(ggfortify)
library(RUVSeq)
library(RColorBrewer)

# making new expression set object for batch effect removal
set <- newSeqExpressionSet(as.matrix(filtered), phenoData = data.frame(x, row.names=colnames(filtered)))

## color similar tissue types for consistency 
colors.order<-colorOrder(x)

abline(h=c(2,-2),lty=2, col="blue",lwd=2)
plotRLE(set, outline=FALSE, ylim=c(-4, 4), col=colors.order)
plotPCA(set, col=colors.order, cex=0.7)
```


```{r fig6, fig.height = 8, fig.width = 8, fig.align = "center"}
## upper quartile normalisation
set <- betweenLaneNormalization(set, which="upper")
save(set, file="upperqNorm2K.RData")
plotRLE(set, outline=FALSE, ylim=c(-4, 4), col=colors.order)
abline(h=c(2,-2),lty=2, col="blue",lwd=2)
plotPCA(set, col=colors.order, cex=0.7)
```

```{r fig7, fig.height = 8, fig.width = 8, fig.align = "center"}

set.RUVg.bp <- RUVg(set, leastVar.genes[1:1000] , k=1)
plotRLE(set.RUVg.bp, outline=FALSE, ylim=c(-4, 4), col=colors.order)
abline(h=c(2,-2),lty=2, col="blue",lwd=2)
plotPCA(set.RUVg.bp, col=colors.order, cex=0.7)

```



```{r fig8, fig.align="center", fig.height=8, fig.width=8}
## normalised expression
source("/Users/suhaib/BaselineMetaAnalysis/OpenTargets/generic_functions.R")
dim(normCounts(set.RUVg.bp))
agg_matrix_norm<-summary_tissues(normCounts(set.RUVg.bp))
plot_heatmap(agg_matrix_norm, name="Normalised")
```


```{r fig9, fig.height = 8, fig.width = 8, fig.align = "center"}
## normalised expression
source("/Users/suhaib/BaselineMetaAnalysis/OpenTargets/generic_functions.R")
dim(counts(set.RUVg.bp))
agg_matrix_raw<-summary_tissues(counts(set.RUVg.bp))
plot_heatmap(agg_matrix_raw, name="Raw")
```

